### PR TITLE
fix: pagination page reset

### LINKED ISSUE #76: Pagination of the extension listing page always resets to page 1
# Actual behaviour
If you open the detail page of an extension and go back via browser or back button, you'll always land back on page 1. This is due to the [immediate watcher of the `sw-extension-store-index` component](https://github.com/shopware/SwagExtensionStore/blob/5b7c39f22e677f070126d99f5be125141075fdd0/src/Resources/app/administration/src/module/sw-extension-store/page/sw-extension-store-index/index.js#L49-L60).

# Expected behaviour
On returning to the listing page, the pagination is not reset, and I can continue searching on the page I left.

### PR DESCRIPTION
**Pull request by FlorianKe**
fixes #76 

No matter which page you are on, clicking back resets the pagination to 1.

### CODE REVIEW

**Review by En0Ma1259 — DISMISSED** [review]

File: src/Resources/app/administration/src/module/sw-extension-store/page/sw-extension-store-index/index.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ export default {
             handler(newValue) {
                 Shopware.Store.get('shopwareExtensions').setSearchValue({
                     key: 'page',
-                    value: 1,
+                    value: Shopware.Store.get('shopwareExtensions').search.page ?? 1,
```
Comment (cyl3x) [inline src/Resources/app/administration/src/module/sw-extension-store/page/sw-extension-store-index/index.js]: what happens if you switch between tabs?

**Review by cyl3x — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]

**Comment by mstegmeyer** [comment]
backport to 6.6.x and 6.5.x?

**Review by En0Ma1259 — APPROVED** [review]
