### PR TITLE
fix: translate iap errors

### LINKED ISSUE #111: Translate IAP errors
Currently, we extract the error details to have a text to display. This should change by translating the error code on our own.

### PR DESCRIPTION
**Pull request by FlorianKe**
fixes #111

### CODE REVIEW

File: src/Exception/InAppPurchaseApiException.php [hunk 1]
```diff
@@ -0,0 +1,34 @@
+<?php declare(strict_types=1);
+
+namespace SwagExtensionStore\Exception;
+
+use GuzzleHttp\Exception\ClientException;
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Store\Exception\StoreApiException;
+
+#[Package('checkout')]
+class InAppPurchaseApiException extends StoreApiException
```
Comment (cyl3x) [inline src/Exception/InAppPurchaseApiException.php]:
```suggestion
class ExtensionStoreApiException extends StoreApiException
```

File: src/Exception/ExtensionStoreException.php [hunk 2]
```diff
@@ -9,15 +9,14 @@
...
 use Shopware\Core\Framework\Store\Exception\InvalidExtensionIdException;
 use Shopware\Core\Framework\Store\Exception\InvalidVariantIdException;
-use Shopware\Core\Framework\Store\Exception\StoreApiException;
 use Symfony\Component\HttpFoundation\Response;
 
 #[Package('checkout')]
 class ExtensionStoreException extends HttpException
 {
-    public static function createStoreApiExceptionFromClientError(ClientException $clientException): StoreApiException
+    public static function createInAppPurchaseApiExceptionFromClientError(ClientException $clientException): InAppPurchaseApiException
```
Comment (cyl3x) [inline src/Exception/ExtensionStoreException.php]:
```suggestion
    public static function createStoreApiExceptionFromClientError(ClientException $clientException): ExtensionStoreApiException
```

File: src/Resources/app/administration/src/module/sw-in-app-purchases/snippet/en.json [hunk 3]
```diff
@@ -23,7 +23,26 @@
...
+      "shopwareplatformexception-88": "In-app feature not found",
+      "shopwareplatformexception-89": "In-app feature already purchased",
+      "shopwareplatformexception-90": "In-app feature not purchasable",
+      "shopwareplatformexception-91": "In-app feature subscription change not allowed",
+      "shopwareplatformexception-92": "In-app feature already pending downgrade",
+      "shopwareplatformexception-93": "Invalid order",
+      "shopwareplatformexception-94": "Insufficient balance",
+      "shopwareplatformexception-95": "GTC not accepted",
+      "shopwareplatformexception-96": "In-app license not found",
+      "cloudadminexception-43": "In-app feature not found",
```
Comment (cyl3x) [inline src/Resources/app/administration/src/module/sw-in-app-purchases/snippet/en.json]: Change all `cloudadminexception` to references:
```suggestion
      "cloudadminexception-43": "@:sw-in-app-purchase-checkout-state.errors.shopwareplatformexception-88",
```

File: src/Resources/app/administration/src/module/sw-in-app-purchases/component/sw-in-app-purchase-checkout-state/index.ts
Comment (cyl3x) [inline src/Resources/app/administration/src/module/sw-in-app-purchases/component/sw-in-app-purchase-checkout-state/index.ts]: Due to the error being a code now, slugifying it is not necessary any more

**Review by cyl3x — APPROVED** [review]

**Review by En0Ma1259 — APPROVED** [review]
